<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net35</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>../../../../tmp/atg_apk/assets/bin/Data/Managed/UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>../../../../tmp/atg_apk/assets/bin/Data/Managed/Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>../../../../tmp/atg_apk/assets/bin/Data/Managed/DOTween.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>../../../../tmp/atg_apk/assets/bin/Data/Managed/System.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>